// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"archi/internal/event/article"
	feed2 "archi/internal/event/feed"
	"archi/internal/event/follow"
	search3 "archi/internal/event/search"
	"archi/internal/event/tag"
	"archi/internal/event/user"
	"archi/internal/repository"
	"archi/internal/repository/cache"
	"archi/internal/repository/dao"
	"archi/internal/repository/dao/search"
	search2 "archi/internal/repository/search"
	"archi/internal/service"
	"archi/internal/service/feed"
	"archi/internal/web"
	"archi/internal/web/middleware/jwt"
	"archi/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	logger := ioc.InitLogger()
	v := ioc.InitGinMiddlewares(handler, logger)
	db := ioc.InitMySQL(logger)
	userDAO := dao.NewGORMUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	client := ioc.InitSaramaClient()
	syncProducer := ioc.InitSyncProducer(client)
	producer := user.NewSaramaSyncProducer(syncProducer)
	userService := service.NewUserService(logger, userRepository, producer)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	smsService := ioc.InitSMSService()
	codeService := service.NewDefaultCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(logger, userService, codeService, handler)
	articleDAO := dao.NewGORMArticleDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewCachedArticleRepository(articleDAO, userRepository, articleCache)
	articleProducer := article.NewSaramaSyncProducer(syncProducer)
	articleService := service.NewDefaultArticleService(articleRepository, articleProducer)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service.NewDefaultInteractiveService(interactiveRepository)
	redisRankingCache := cache.NewRedisRankingCache(cmdable)
	localRankingCache := cache.NewLocalRankingCache()
	rankingRepository := repository.NewCachedRankingRepository(redisRankingCache, localRankingCache)
	rankingService := service.NewBatchRankingService(interactiveService, articleService, rankingRepository)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, rankingService, logger)
	commentDAO := dao.NewGORMCommentDAO(db)
	commentRepository := repository.NewCachedCommentRepository(commentDAO, logger)
	commentService := service.NewDefaultCommentService(commentRepository)
	commentHandler := web.NewCommentHandler(commentService, logger)
	followProducer := follow.NewFollowEventProducer(syncProducer)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewCachedFollowRepository(followRelationDao, followCache, logger)
	followRelationService := service.NewDefaultFollowRelationService(followProducer, followRepository, logger)
	followHandler := web.NewFollowHandler(followRelationService, logger)
	tagDAO := dao.NewGORMTagDAO(db)
	tagCache := cache.NewRedisTagCache(cmdable)
	tagRepository := repository.NewCachedTagRepository(tagDAO, tagCache, logger)
	tagProducer := tag.NewSaramaSyncProducer(syncProducer)
	tagService := service.NewDefaultTagService(tagRepository, tagProducer, logger)
	tagHandler := web.NewTagHandler(tagService, logger)
	elasticClient := ioc.InitESClient()
	searchUserDAO := search.NewESUserDAO(elasticClient)
	searchUserRepository := search2.NewDefaultUserRepository(searchUserDAO)
	searchArticleDAO := search.NewESArticleDAO(elasticClient)
	searchTagDAO := search.NewESTagDAO(elasticClient)
	searchArticleRepository := search2.NewDefaultArticleRepository(searchArticleDAO, searchTagDAO)
	searchService := service.NewDefaultSearchService(searchUserRepository, searchArticleRepository)
	searchHandler := web.NewSearchHandler(searchService)
	feedPullEventDAO := dao.NewFeedPullEventDAO(db)
	feedPushEventDAO := dao.NewFeedPushEventDAO(db)
	feedEventCache := cache.NewFeedEventCache(cmdable)
	feedEventRepo := repository.NewFeedEventRepo(feedPullEventDAO, feedPushEventDAO, feedEventCache)
	v2 := ioc.RegisterFeedHandler(feedEventRepo, followRelationService)
	feedService := feed.NewFeedService(feedEventRepo, v2)
	feedHandler := web.NewFeedHandler(feedService, logger)
	engine := ioc.InitWebEngine(v, logger, userHandler, articleHandler, commentHandler, followHandler, tagHandler, searchHandler, feedHandler)
	readEventConsumer := article.NewReadEventConsumer(interactiveRepository, client, logger)
	anyDAO := search.NewESAnyDAO(elasticClient)
	anyRepository := search2.NewDefaultAnyRepository(anyDAO)
	syncService := service.NewDefaultSyncService(anyRepository, searchUserRepository, searchArticleRepository)
	userConsumer := search3.NewUserConsumer(client, logger, syncService)
	articleConsumer := search3.NewArticleConsumer(client, logger, syncService)
	syncDataEventConsumer := search3.NewSyncDataEventConsumer(syncService, client, logger)
	followEventConsumer := feed2.NewFollowEventConsumer(feedService, client, logger)
	v3 := ioc.InitConsumers(readEventConsumer, userConsumer, articleConsumer, syncDataEventConsumer, followEventConsumer)
	rlockClient := ioc.InitRlockClient(cmdable)
	rankingJob := ioc.InitRankingJob(rankingService, rlockClient, logger)
	cron := ioc.InitJobs(logger, rankingJob)
	app := &App{
		engine:    engine,
		consumers: v3,
		cron:      cron,
	}
	return app
}

// wire.go:

var thirdPartyProviderSet = wire.NewSet(ioc.InitLogger, ioc.InitMySQL, ioc.InitRedis, ioc.InitRlockClient, ioc.InitSaramaClient, ioc.InitESClient)

var userSvcProviderSet = wire.NewSet(cache.NewRedisUserCache, dao.NewGORMUserDAO, repository.NewCachedUserRepository, service.NewUserService)

var codeSvcProviderSet = wire.NewSet(cache.NewRedisCodeCache, repository.NewCachedCodeRepository, ioc.InitSMSService, service.NewDefaultCodeService)

var articleSvcProviderSet = wire.NewSet(cache.NewRedisArticleCache, dao.NewGORMArticleDAO, repository.NewCachedArticleRepository, service.NewDefaultArticleService)

var interactiveSvcProviderSet = wire.NewSet(cache.NewRedisInteractiveCache, dao.NewGORMInteractiveDAO, repository.NewCachedInteractiveRepository, service.NewDefaultInteractiveService)

var rankingSvcProviderSet = wire.NewSet(cache.NewRedisRankingCache, cache.NewLocalRankingCache, repository.NewCachedRankingRepository, service.NewBatchRankingService)

var commentSvcProviderSet = wire.NewSet(dao.NewGORMCommentDAO, repository.NewCachedCommentRepository, service.NewDefaultCommentService)

var followSvcProviderSet = wire.NewSet(cache.NewRedisFollowCache, dao.NewGORMFollowRelationDAO, repository.NewCachedFollowRepository, service.NewDefaultFollowRelationService)

var tagSvcProviderSet = wire.NewSet(cache.NewRedisTagCache, dao.NewGORMTagDAO, repository.NewCachedTagRepository, service.NewDefaultTagService)

var searchSvcProviderSet = wire.NewSet(search.NewESUserDAO, search.NewESTagDAO, search.NewESArticleDAO, search2.NewDefaultUserRepository, search2.NewDefaultArticleRepository, service.NewDefaultSearchService, search.NewESAnyDAO, search2.NewDefaultAnyRepository, service.NewDefaultSyncService)

var feedSvcProviderSet = wire.NewSet(cache.NewFeedEventCache, dao.NewFeedPullEventDAO, dao.NewFeedPushEventDAO, repository.NewFeedEventRepo, feed.NewFeedService, ioc.RegisterFeedHandler)

var eventsProviderSet = wire.NewSet(ioc.InitSyncProducer, ioc.InitConsumers, search3.NewSyncDataEventConsumer, article.NewSaramaSyncProducer, article.NewReadEventConsumer, search3.NewArticleConsumer, tag.NewSaramaSyncProducer, user.NewSaramaSyncProducer, search3.NewUserConsumer, follow.NewFollowEventProducer, feed2.NewFollowEventConsumer)

var handlerProviderSet = wire.NewSet(jwt.NewRedisJWTHandler, web.NewUserHandler, web.NewArticleHandler, web.NewCommentHandler, web.NewFollowHandler, web.NewTagHandler, web.NewSearchHandler, web.NewFeedHandler)

var jobProviderSet = wire.NewSet(ioc.InitRankingJob, ioc.InitJobs)
